apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ms-teams.fullname" . }}
  labels:
    {{- include "ms-teams.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ms-teams.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ms-teams.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/teleport-plugin
            - start
            - "--config"
            - "/etc/teleport-ms-teams.toml"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/teleport-ms-teams.toml
              subPath: teleport-ms-teams.toml
            - name: auth-id
              mountPath: /var/lib/teleport/plugins/ms-teams/auth_id
              subPath: {{ .Values.teleport.identitySecretPath }}
            - name: {{ .Values.secretVolumeName }}
              mountPath: /var/lib/teleport/plugins/ms-teams/appSecret
              subPath: {{ .Values.msTeams.appSecretFromSecretPath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "ms-teams.fullname" . }}
            defaultMode: 0600
        - name: auth-id
          secret:
            secretName: "{{ .Values.teleport.identitySecretName }}"
            defaultMode: 0600
        - name: {{ .Values.secretVolumeName }}
          secret:
            secretName: "{{ coalesce .Values.msTeams.appSecretFromSecret (printf "%s-secret" (include "ms-teams.fullname" .)) }}"
            defaultMode: 0600
