{{ if or .Values.mailgun.enabled .Values.smtp.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "email.fullname" . }}-password
data:
  {{- if .Values.mailgun.enabled }}
  mailgunPrivateKey: {{ .Values.mailgun.privateKey | b64enc }}
  {{- end }}
  {{- if .Values.smtp.enabled }}
  smtpPassword: {{ b64enc .Values.smtp.password }}
  {{- end }}
{{- end }}
